### PR TITLE
Update TS information

### PR DESCRIPTION
**Pull request by eric-burel**
<details>
  <summary>📦 Published PR as canary version: <code>0.0.18--canary.33.6e6a4b1.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/testing-react@0.0.18--canary.33.6e6a4b1.0
  # or 
  yarn add @storybook/testing-react@0.0.18--canary.33.6e6a4b1.0
  ```
</details>

### CODE REVIEW

**Comment by yannbf** [comment]
Thanks a lot @eric-burel !

**Comment by eric-burel** [comment]
I just change json to jsonc for the codeblock display (I have write rights on Storybook project so I'll simply commit on `main` branch to avoid back and forth PR)

**Comment by yannbf** [comment]
> I just change json to jsonc for the codeblock display (I have write rights on Storybook project so I'll simply commit on `main` branch to avoid back and forth PR)

Oh, please don't do that. I always try to avoid pushing directly to main, and now that small change actually made a release with no actual feature or fix. Next time add [skip ci] to the commit message at least :D

**Comment by yannbf** [comment]
Also for some reason the version bump after your push was done by https://github.com/saurabhsahu-tcs. That's pretty odd.

**Comment by eric-burel** [comment]
Ah man I'm dumb I should have expected that sorry! (first time contributing to a project this big)

**Comment by yannbf** [comment]
> Ah man I'm dumb I should have expected that sorry! (first time contributing to a project this big)

It's all ok! The change was quite simple and won't impact people anyway. But rule of thumb, never push to main unless you really understand the landscape of the project and you're clearly communicating with the maintainers. It's super fine to make extra PRs for typos!

Thanks for using the lib and for your contributions :))

**Pull request merged**
