### PR TITLE
Update storybook pkg

### PR DESCRIPTION
**Pull request by sakit0**
Issue: https://github.com/storybookjs/testing-react/issues/106

## What Changed

- Update Storybooks pkg
- WebProjectAnnotations @storybook/preview-web to @storybook/store.
- skipLibCheck to false

## Checklist

Check the ones applicable to your change:

- [ ] Tests are updated
- [ ] Documentation is updated

## Change Type

Indicate the type of change your pull request is:

- [ ] `documentation`
- [ ] `patch`
- [ ] `minor`
- [x] `major`

### CODE REVIEW

**Comment by sakit0** [comment]
The build now succeeds.
However, if skipLibCheck : false, the build fails.
I think it would be better to set skipLibCheck : false.

**Comment by clintandrewhall** [comment]
FYI: https://github.com/storybookjs/storybook/pull/19048 is also pending, which resolves it for shorter-term patch release.

**Comment by sakit0** [comment]
@clintandrewhall 
thank you!
I will fix it to use when it is released.

**Comment by sakit0** [comment]
skipLibCheck was set to false.
This fixed the error.
https://github.com/storybookjs/testing-react/pull/115#issuecomment-1226866885

The version of @storybook/csf was out of sync with @storybook/client-api and @storybook/store's dependencies on @storybook/csf, so we aligned them.

**Comment by yannbf** [comment]
Hey @sakit0, thank you so much for your contribution! Given that Storybook 7.0 has reached beta, in the efforts of supporting it, I released [`2.0.0-next.0`](https://github.com/storybookjs/testing-react/releases/tag/v2.0.0-next.0) which supports Storybook 7 and does most changes you did in this PR, but in the new structure for Storybook 7.0.

Given that this PR is a breaking change for users that use `1.x.x`, and we now have a `2.0.0` version that supports Storybook 7.0, and getting this released is going to be a lot of effort, so I'd rather have users migrate their Storybook to 7.0 instead, and they won't have any issues with testing-react v2.

I hope you understand, and I'll be closing this PR. Thank you so much once again for your time!

**Pull request closed without merging**
