### PR TITLE
feat: support CSF3 format

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #31

Add support for CSF3

### Features

Storybook released [CSF3](https://storybook.js.org/blog/component-story-format-3-0/), where the story can also be an object. This is now supported in @storybook/testing-react. CSF3 also brings a new function called `play`, where you can write automated interactions to the story.

In @storybook/testing-react, the `play` does not run automatically for you, but rather comes in the returned component, and you can execute it as you please.

Consider the following example:

```tsx
export const InputFieldFilled: Story<InputFieldProps> = {
  play: async () => {
    await userEvent.type(screen.getByRole('textbox'), 'Hello world!');
  },
};
```

You can use the play function like this:

```tsx
const { InputFieldFilled } = composeStories(stories);

test('renders with play function', async () => {
  render(<InputFieldFilled />);

  // play an interaction that fills the input
  await InputFieldFilled.play!();

  const input = screen.getByRole('textbox') as HTMLInputElement;
  expect(input.value).toEqual('Hello world!');
});
```

<details>
  <summary>📦 Published PR as canary version: <code>0.0.19--canary.37.ed1f139.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/testing-react@0.0.19--canary.37.ed1f139.0
  # or 
  yarn add @storybook/testing-react@0.0.19--canary.37.ed1f139.0
  ```
</details>

### CODE REVIEW

**Comment by loeck** [comment]
Thanks a lot for this PR, look good on my project with `0.0.19--canary.37.24ee251.0` now 🙏 (only few simple tests, so maybe I don't handle lot of cases)

**Comment by yannbf** [comment]
> Thanks a lot for this PR, look good on my project with `0.0.19--canary.37.24ee251.0` now 🙏 (only few simple tests, so maybe I don't handle lot of cases)

Thank you for trying it out! I'll be updating this PR soon to support CSF3 types, I'll keep you posted!

**Comment by benbender** [comment]
Same for me - works like a charm (besides the type-problem). Thanks you for your work! 🥇

**Comment by yannbf** [comment]
@loeck @benbender thank you so much!! both for using the lib and for helping out testing. Support like yours is what gives me energy to keep improving the library ❤️ 

[0.0.21 has been released](https://github.com/storybookjs/testing-react/releases/tag/v0.0.21) and it includes proper typings. Should work well, but please let me know if you encounter any issues :)

**Pull request merged**
