### PR TITLE
feat: add args as a result from composed story

### PR DESCRIPTION
**Pull request by yannbf**
Using components from composeStories is cool but sometimes people might want to get their args as well. Currently they do not exist, and this PR adds support for that.

use case:
```jsx
const { Secondary } = composeStories(stories)

it('should do something', () => {
  render(<Secondary />);
  const buttonElement = screen.getByRole("button");
  expect(buttonElement.textContent).toEqual(Secondary.args!.label);
});
```

<details>
  <summary>📦 Published PR as canary version: <code>0.0.15--canary.19.861a04c.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/testing-react@0.0.15--canary.19.861a04c.0
  # or 
  yarn add @storybook/testing-react@0.0.15--canary.19.861a04c.0
  ```
</details>

### CODE REVIEW

**Comment by yannbf** [comment]
@tmeasday would you be so kind to give your opinion on this? thanks!

**Comment by tmeasday** [comment]
Makes sense to me @yannbf

**Comment by yannbf** [comment]
> Makes sense to me @yannbf

Thanks! Do you think more properties should be returned together? such as the parameters as well?

**Comment by tmeasday** [comment]
Yeah, I guess it would make sense to put `parameters` and `decorators`(?) on there too? What about `argTypes`?

**Comment by yannbf** [comment]
> Yeah, I guess it would make sense to put `parameters` and `decorators`(?) on there too? What about `argTypes`?

What's the use case you see for them? I guess if this mechanism becomes useful for a storyshots 2.0 it's nice, but for testing do you see use for argTypes or decorators?

**Comment by tmeasday** [comment]
- decorators: just completeness I guess, I can't really think of a good reason to test them.
- argTypes: I suppose folks might want to test their argTypes are right for documentation purposes. But then we aren't going to have docgen info and so the argTypeEnhancers aren't going to work. So perhaps there's no point.

**Comment by yannbf** [comment]
> * decorators: just completeness I guess, I can't really think of a good reason to test them.
> * argTypes: I suppose folks might want to test their argTypes are right for documentation purposes. But then we aren't going to have docgen info and so the argTypeEnhancers aren't going to work. So perhaps there's no point.

I added args, decorators and parameters. Given that argtypes are not processed within the library, I'm not including but if we come to a point where it makes sense, we can add it! I'll merge as is.

**Pull request merged**
